"""empty message

Revision ID: 32128aad5049
Revises: 5bdef82cee1d
Create Date: 2026-09-22 18:44:31.929700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32128aad5049'
down_revision = '5bdef82cee1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('item_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_description', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
